# Migrations between countries

#### In this notebook we will process a .xlsx file that contains the migrations between countries for the years 1990, 1995, 2000, 2005, 2010, 2015 and an estimate for the year 2017

#### We have a matrix with the following structure:

    Year                    — year for which there is information about migrations
    Country of destination  — country that receives x migrants from other countries
    Country of origin 1     — Country 1 from which migrate n number of people
    Country of origin 2     — Country 2 from which migrate n number of people
    ...                     
    Country of origien n    — Country n from which migrate n number of people
    
- To begin, we import the packages for data processing. <br>
If necessary, run in the anaconda console "pip install (package name)"

In [1]:
import pandas as pd

- We read the .csv file and convert all the columns of source countries into one.

In [2]:
df = pd.read_csv("01_Input_Migrations.csv", sep = ";", encoding = 'latin1')
df.head()

,Year,Country_Destination,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,...,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe
0,1990,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2027.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1990,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1990,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,167905.0,2593.0,NaN,NaN
3,1990,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
4,1990,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
years   = list(df['Year'])
destiny = list(df['Country_Destination'])
origin  = list(df)[2:len(df.columns)]
    
year                = []
country_origin      = []
country_destination = []
people              = []

for i in range(0, len(df)):
    for o in origin:
        aux_people = df.loc[i, o]
        
        year.append(years[i])
        country_origin.append(o)
        country_destination.append(destiny[i])
        people.append(aux_people)
            
df2 = pd.DataFrame({'years'              : year,
                    'country_origin'     : country_origin,
                    'country_destination': country_destination,
                    'people'             : people})

df2 = df2[df2['people'].notnull()]
df2['people'] = df2['people'].astype(int)

df2.to_csv('01_Output_Migrations.csv', header = True, sep = ';', encoding = 'latin1', index = False)